"""P0-BE-09 baseline: full current schema

Revision ID: 6a7265365533
Revises: 
Create Date: 2026-08-18 15:32:47.712855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a7265365533'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conflict_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('attribute', sa.String(length=255), nullable=False),
    sa.Column('scope_product', sa.String(length=255), nullable=True),
    sa.Column('scope_version', sa.String(length=255), nullable=True),
    sa.Column('ko_ids', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('resolved_ko_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conflict_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conflict_tasks_status'), ['status'], unique=False)

    op.create_table('graph_entities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('normalized', sa.String(length=255), nullable=True),
    sa.Column('ko_ids', sa.Text(), nullable=True),
    sa.Column('extra', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('graph_entities', schema=None) as batch_op:
        batch_op.create_index('ix_ge_type_name', ['entity_type', 'name'], unique=False)
        batch_op.create_index(batch_op.f('ix_graph_entities_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_graph_entities_name'), ['name'], unique=False)

    op.create_table('knowledge_debts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('debt_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('related_question', sa.Text(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_debts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_debts_debt_type'), ['debt_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_debts_status'), ['status'], unique=False)

    op.create_table('notebooks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('group_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notebooks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notebooks_group_id'), ['group_id'], unique=False)

    op.create_table('query_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('intent', sa.String(length=50), nullable=True),
    sa.Column('judgment_passed', sa.Boolean(), nullable=True),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('feedback', sa.String(length=16), nullable=True),
    sa.Column('ko_citations', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('is_local', sa.Boolean(), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('graph_relations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=False),
    sa.Column('relation_type', sa.String(length=50), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('ko_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['graph_entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['graph_entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('graph_relations', schema=None) as batch_op:
        batch_op.create_index('ix_gr_source_target', ['source_id', 'target_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_graph_relations_relation_type'), ['relation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_graph_relations_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_graph_relations_target_id'), ['target_id'], unique=False)

    op.create_table('pages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('notebook_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('source_id', sa.String(length=255), nullable=True),
    sa.Column('source_path', sa.Text(), nullable=True),
    sa.Column('source_space_id', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('source_file_hash', sa.String(length=64), nullable=True),
    sa.Column('source_file_size', sa.Integer(), nullable=True),
    sa.Column('source_mime_type', sa.String(length=127), nullable=True),
    sa.Column('source_content', sa.Text(), nullable=True),
    sa.Column('source_content_hash', sa.String(length=64), nullable=True),
    sa.Column('source_markdown_hash', sa.String(length=64), nullable=True),
    sa.Column('source_pipeline_version', sa.String(length=127), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('indexed_content_hash', sa.String(length=64), nullable=True),
    sa.Column('index_dirty', sa.Boolean(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('compile_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['notebook_id'], ['notebooks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pages_notebook_id'), ['notebook_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pages_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index('ux_pages_source_type_source_id', ['source_type', 'source_id'], unique=True)

    op.create_table('user_groups',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('group_name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_groups_group_name'), ['group_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_groups_user_id'), ['user_id'], unique=False)

    op.create_table('graph_edges',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('edge_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['pages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('graph_edges', schema=None) as batch_op:
        batch_op.create_index('ix_graph_edges_pair', ['source_id', 'target_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_graph_edges_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_graph_edges_target_id'), ['target_id'], unique=False)

    op.create_table('knowledge_objects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('structured', sa.Text(), nullable=True),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('valid_from', sa.DateTime(), nullable=True),
    sa.Column('valid_to', sa.DateTime(), nullable=True),
    sa.Column('superseded_by', sa.String(length=36), nullable=True),
    sa.Column('last_transition_reason', sa.Text(), nullable=True),
    sa.Column('source_page_id', sa.String(length=36), nullable=True),
    sa.Column('source_locator', sa.String(length=255), nullable=True),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('evidence_ids', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_page_id'], ['pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_objects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_objects_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_objects_source_page_id'), ['source_page_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_objects_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_objects_type'), ['type'], unique=False)
        batch_op.create_index('ix_ko_scope_product', ['scope'], unique=False)
        batch_op.create_index('ix_ko_type_status', ['type', 'status'], unique=False)

    op.create_table('page_chunks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('page_id', sa.String(length=36), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_type', sa.String(length=32), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('image_id', sa.String(length=255), nullable=True),
    sa.Column('embedding', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('page_chunks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_page_chunks_page_id'), ['page_id'], unique=False)
        batch_op.create_index('ix_page_chunks_page_idx', ['page_id', 'chunk_index'], unique=False)

    op.create_table('ko_chunks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ko_id', sa.String(length=36), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['ko_id'], ['knowledge_objects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ko_chunks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ko_chunks_ko_id'), ['ko_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ko_chunks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ko_chunks_ko_id'))

    op.drop_table('ko_chunks')
    with op.batch_alter_table('page_chunks', schema=None) as batch_op:
        batch_op.drop_index('ix_page_chunks_page_idx')
        batch_op.drop_index(batch_op.f('ix_page_chunks_page_id'))

    op.drop_table('page_chunks')
    with op.batch_alter_table('knowledge_objects', schema=None) as batch_op:
        batch_op.drop_index('ix_ko_type_status')
        batch_op.drop_index('ix_ko_scope_product')
        batch_op.drop_index(batch_op.f('ix_knowledge_objects_type'))
        batch_op.drop_index(batch_op.f('ix_knowledge_objects_status'))
        batch_op.drop_index(batch_op.f('ix_knowledge_objects_source_page_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_objects_content_hash'))

    op.drop_table('knowledge_objects')
    with op.batch_alter_table('graph_edges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_graph_edges_target_id'))
        batch_op.drop_index(batch_op.f('ix_graph_edges_source_id'))
        batch_op.drop_index('ix_graph_edges_pair')

    op.drop_table('graph_edges')
    with op.batch_alter_table('user_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_groups_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_groups_group_name'))

    op.drop_table('user_groups')
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.drop_index('ux_pages_source_type_source_id')
        batch_op.drop_index(batch_op.f('ix_pages_updated_at'))
        batch_op.drop_index(batch_op.f('ix_pages_notebook_id'))

    op.drop_table('pages')
    with op.batch_alter_table('graph_relations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_graph_relations_target_id'))
        batch_op.drop_index(batch_op.f('ix_graph_relations_source_id'))
        batch_op.drop_index(batch_op.f('ix_graph_relations_relation_type'))
        batch_op.drop_index('ix_gr_source_target')

    op.drop_table('graph_relations')
    op.drop_table('users')
    op.drop_table('query_logs')
    with op.batch_alter_table('notebooks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notebooks_group_id'))

    op.drop_table('notebooks')
    with op.batch_alter_table('knowledge_debts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_debts_status'))
        batch_op.drop_index(batch_op.f('ix_knowledge_debts_debt_type'))

    op.drop_table('knowledge_debts')
    with op.batch_alter_table('graph_entities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_graph_entities_name'))
        batch_op.drop_index(batch_op.f('ix_graph_entities_entity_type'))
        batch_op.drop_index('ix_ge_type_name')

    op.drop_table('graph_entities')
    with op.batch_alter_table('conflict_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conflict_tasks_status'))

    op.drop_table('conflict_tasks')
    # ### end Alembic commands ###
