"""P1_BE_01 evidence tables

Revision ID: 9e5ddaba4e2c
Revises: 6a7265365533
Create Date: 2026-08-18 16:23:05.377613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e5ddaba4e2c'
down_revision: Union[str, Sequence[str], None] = '6a7265365533'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_observations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('asset_id', sa.String(length=255), nullable=False),
    sa.Column('observation_type', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('extraction_method', sa.String(length=32), nullable=True),
    sa.Column('model_name', sa.String(length=127), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('needs_review', sa.Boolean(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('asset_observations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asset_observations_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_observations_content_hash'), ['content_hash'], unique=False)

    op.create_table('evidence_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_page_id', sa.String(length=36), nullable=True),
    sa.Column('source_chunk_id', sa.String(length=36), nullable=True),
    sa.Column('source_asset_id', sa.String(length=255), nullable=True),
    sa.Column('evidence_type', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('locator_json', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('extraction_method', sa.String(length=32), nullable=True),
    sa.Column('model_name', sa.String(length=127), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('needs_review', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_chunk_id'], ['page_chunks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_page_id'], ['pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_items_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_items_source_asset_id'), ['source_asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_items_source_chunk_id'), ['source_chunk_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_items_source_page_id'), ['source_page_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_items_status'), ['status'], unique=False)
        batch_op.create_index('ix_evidence_page_status', ['source_page_id', 'status'], unique=False)

    op.create_table('evidence_links',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('card_id', sa.String(length=36), nullable=True),
    sa.Column('legacy_ko_id', sa.String(length=36), nullable=True),
    sa.Column('claim_id', sa.String(length=36), nullable=True),
    sa.Column('evidence_id', sa.String(length=36), nullable=False),
    sa.Column('link_type', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['legacy_ko_id'], ['knowledge_objects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence_links', schema=None) as batch_op:
        batch_op.create_index('ix_elink_ko_evidence', ['legacy_ko_id', 'evidence_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_links_card_id'), ['card_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_links_claim_id'), ['claim_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_links_evidence_id'), ['evidence_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_links_legacy_ko_id'), ['legacy_ko_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evidence_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_links_legacy_ko_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_links_evidence_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_links_claim_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_links_card_id'))
        batch_op.drop_index('ix_elink_ko_evidence')

    op.drop_table('evidence_links')
    with op.batch_alter_table('evidence_items', schema=None) as batch_op:
        batch_op.drop_index('ix_evidence_page_status')
        batch_op.drop_index(batch_op.f('ix_evidence_items_status'))
        batch_op.drop_index(batch_op.f('ix_evidence_items_source_page_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_items_source_chunk_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_items_source_asset_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_items_content_hash'))

    op.drop_table('evidence_items')
    with op.batch_alter_table('asset_observations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asset_observations_content_hash'))
        batch_op.drop_index(batch_op.f('ix_asset_observations_asset_id'))

    op.drop_table('asset_observations')
    # ### end Alembic commands ###
